// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//



#include "app/framework/include/af.h"
#include "app/framework/cli/custom-cli.h"


void emAfGroupsServerCliClear(void);
void emAfGroupsServerCliPrint(void);
void emAfMfglibEnableMfglib(void);
void emAfMfglibProgramEuiCommand(void);
void emAfMfglibSendCommand(void);
void emAfMfglibSendMessageCommand(void);
void emAfMfglibSetChannelCommand(void);
void emAfMfglibSetOptions(void);
void emAfMfglibSetPowerAndModeCommand(void);
void emAfMfglibSleepCommand(void);
void emAfMfglibStartCommand(void);
void emAfMfglibStatusCommand(void);
void emAfMfglibStopCommand(void);
void emAfMfglibStreamStartCommand(void);
void emAfMfglibStreamStopCommand(void);
void emAfMfglibToneStartCommand(void);
void emAfMfglibToneStopCommand(void);
void emAfOtaClientPrintState(void);
void emAfOtaImageDelete(void);
void emAfOtaPrintAllImages(void);
void emAfOtaReloadStorageDevice(void);
void emAfOtaStorageDataPrint(void);
void emAfOtaStorageInfoPrint(void);
#if defined(EMBER_AF_PLUGIN_OTA_STORAGE_SIMPLE_EEPROM) && (EMBER_AF_PLUGIN_OTA_STORAGE_SIMPLE_EEPROM_READ_MODIFY_WRITE_SUPPORT == FALSE)
void emAfOtaWipeStorageDevice(void);
#endif
void emAfPluginConnectionManagerSetForceShortPollCommand(void);
void emAfPluginIdentifyCliPrint(void);
void emAfPluginReportingCliAdd(void);
void emAfPluginReportingCliClear(void);
void emAfPluginReportingCliClearLastReportTime(void);
void emAfPluginReportingCliPrint(void);
void emAfPluginReportingCliRemove(void);
void emAfPluginScenesServerClear(void);
void emAfPluginScenesServerPrintInfo(void);
void emAfSendImageBlockRequestTest(void);
void emberAfPluginGreenPowerClientAddGroupcastSink(void);
void emberAfPluginGreenPowerClientAddSink(void);
void emberAfPluginGreenPowerClientClearProxyTable(void);
void emberAfPluginGreenPowerClientDuplicateFilteringTest(void);
void emberAfPluginGreenPowerClientPrintProxyTable(void);
void emberAfPluginGreenPowerClientRemoveProxyTableEntry(void);
void emberAfPluginGreenPowerClientSetKey(void);
void emberAfPluginGreenPowerClientSetProxyEntry(void);
void emberAfPluginNetworkSteeringChannelAddOrSubtractCommand(void);
void emberAfPluginNetworkSteeringChannelSetCommand(void);
void emberAfPluginNetworkSteeringStartCommand(void);
void emberAfPluginNetworkSteeringStatusCommand(void);
void emberAfPluginNetworkSteeringStopCommand(void);
void networkLeaveCommand(void);
void otaCliBootload(void);
void otaCliVerify(void);
void otaPrintClientInfo(void);
void otaSendUpgradeRequest(void);
void otaStartClientCommand(void);
void otaStopClientCommand(void);
void printBootloaderInfoCommand(void);
void setPageRequest(void);
void setPausePercentage(void);
static void zclBasicGlsrCommand(void) {
  zclSimpleServerCommand( ZCL_BASIC_CLUSTER_ID,
                          ZCL_GET_LOCALES_SUPPORTED_RESPONSE_COMMAND_ID);
}

void zclIdentifyOnOffCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTableZclIdentifyOffCommandArguments[] = {
  "The endpoint on which to stop identifying",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTableZclIdentifyOnCommandArguments[] = {
  "The endpoint on the device which should begin identifying",
  "The number of seconds to spend identifying",
  NULL
};
#endif

static EmberCommandEntry emberCommandTableZclIdentifyCommands[] = {
  emberCommandEntryActionWithDetails("off", zclIdentifyOnOffCommand, "u", "Writes the IdentifyTime attribute", emberCommandTableZclIdentifyOffCommandArguments),
  emberCommandEntryActionWithDetails("on", zclIdentifyOnOffCommand, "uv", "Writes the IdentifyTime attribute", emberCommandTableZclIdentifyOnCommandArguments),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTableZclBasicGlsrCommandArguments[] = {
  "discovery complete",
  "locale supported",
  "",
  NULL
};
#endif

static EmberCommandEntry emberCommandTableZclBasicCommands[] = {
  emberCommandEntryActionWithDetails("glsr", zclBasicGlsrCommand, "ub*", "The locales supported response command is sent in response to a get lo ...", emberCommandTableZclBasicGlsrCommandArguments),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTableZclCommands[] = {
  emberCommandEntrySubMenu("basic", emberCommandTableZclBasicCommands, ""),
  emberCommandEntrySubMenu("identify", emberCommandTableZclIdentifyCommands, ""),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTablePluginScenesCommands[] = {
  emberCommandEntryActionWithDetails("clear", emAfPluginScenesServerClear, "", "Clear the scenes table on every endpoint.", NULL),
  emberCommandEntryActionWithDetails("print", emAfPluginScenesServerPrintInfo, "", "Print information about the contents of the scenes table.", NULL),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginReportingAddCommandArguments[] = {
  "The local endpoint from which the attribute is reported.",
  "The cluster where the attribute is located.",
  "The id of the attribute being reported.",
  "0 for client-side attributes or 1 for server-side attributes.",
  "The minimum reporting interval, measured in seconds.",
  "The maximum reporting interval, measured in seconds.",
  "The minimum change to the attribute that will result in a report being ...",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginReportingRemoveCommandArguments[] = {
  "The index of the report to be removed.",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginReportingCommands[] = {
  emberCommandEntryActionWithDetails("add", emAfPluginReportingCliAdd, "uvvuvvw", "Add a new entry to the report table.", emberCommandTablePluginReportingAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", emAfPluginReportingCliClear, "", "Clear all entries from the report table.", NULL),
  emberCommandEntryActionWithDetails("clear-last-report-time", emAfPluginReportingCliClearLastReportTime, "", "Clear last report time of attributes.", NULL),
  emberCommandEntryActionWithDetails("print", emAfPluginReportingCliPrint, "", "Print the report table.", NULL),
  emberCommandEntryActionWithDetails("remove", emAfPluginReportingCliRemove, "u", "Remove an entry from the report table.", emberCommandTablePluginReportingRemoveCommandArguments),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTablePluginOtaStorageEepromCommands[] = {
#if defined(EMBER_AF_PLUGIN_OTA_STORAGE_SIMPLE_EEPROM) && (EMBER_AF_PLUGIN_OTA_STORAGE_SIMPLE_EEPROM_READ_MODIFY_WRITE_SUPPORT == FALSE)
  emberCommandEntryActionWithDetails("wipe", emAfOtaWipeStorageDevice, "", "Wipes all data in the storage device.", NULL),
#endif
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginOtaStorageCommonDataPrintCommandArguments[] = {
  "The index of the image to print its data.",
  "The offset into the OTA image that will be printed.",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginOtaStorageCommonDeleteCommandArguments[] = {
  "The index at which to begin bootloading the image",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginOtaStorageCommonCommands[] = {
  emberCommandEntryActionWithDetails("data-print", emAfOtaStorageDataPrint, "uw", "Print arbitray bytes of the OTA image on disk.", emberCommandTablePluginOtaStorageCommonDataPrintCommandArguments),
  emberCommandEntryActionWithDetails("delete", emAfOtaImageDelete, "u", "Deletes the image at the specified index.", emberCommandTablePluginOtaStorageCommonDeleteCommandArguments),
  emberCommandEntryActionWithDetails("printImages", emAfOtaPrintAllImages, "", "Prints the images.", NULL),
  emberCommandEntryActionWithDetails("reload", emAfOtaReloadStorageDevice, "", "Reload the storage device.", NULL),
  emberCommandEntryActionWithDetails("storage-info", emAfOtaStorageInfoPrint, "", "Print information about the storage device.", NULL),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginOtaClientBootloadCommandArguments[] = {
  "The index at which to begin bootloading the image",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginOtaClientPageRequestCommandArguments[] = {
  "boolean value turning on (1) or off (0) the page request flag",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginOtaClientPauseAtCommandArguments[] = {
  "stop download percentage",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginOtaClientVerifyCommandArguments[] = {
  "The index at which to begin verification of the image",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginOtaClientCommands[] = {
  emberCommandEntryActionWithDetails("block-test", emAfSendImageBlockRequestTest, "", "Sends an image block request for a file the server should not hav ...", NULL),
  emberCommandEntryActionWithDetails("bootload", otaCliBootload, "u", "Bootloads the image at the specified index by calling the OTA bootload ...", emberCommandTablePluginOtaClientBootloadCommandArguments),
  emberCommandEntryActionWithDetails("info", otaPrintClientInfo, "", "Prints the manufacturer ID, Image Type ID, and Version information tha ...", NULL),
  emberCommandEntryActionWithDetails("page-request", setPageRequest, "u", "", emberCommandTablePluginOtaClientPageRequestCommandArguments),
  emberCommandEntryActionWithDetails("pause-at", setPausePercentage, "u", "", emberCommandTablePluginOtaClientPauseAtCommandArguments),
  emberCommandEntryActionWithDetails("start", otaStartClientCommand, "", "Starts the ota client state machin ...", NULL),
  emberCommandEntryActionWithDetails("status", emAfOtaClientPrintState, "", "Prints information on the current state of the OTA client download.", NULL),
  emberCommandEntryActionWithDetails("stop", otaStopClientCommand, "", "Stops the OTA state machine", NULL),
  emberCommandEntryActionWithDetails("upgrade-request", otaSendUpgradeRequest, "", "Send an OTA server an UpgradeEndRequest", NULL),
  emberCommandEntryActionWithDetails("verify", otaCliVerify, "u", "Perform signature verification on the image at the specified index", emberCommandTablePluginOtaClientVerifyCommandArguments),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTablePluginOtaBootloadCommands[] = {
  emberCommandEntryActionWithDetails("info", printBootloaderInfoCommand, "", "Prints info about the installed bootloader.", NULL),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginNetworkSteeringMaskAddCommandArguments[] = {
  "The channel mask to add a channel to.",
  "The channel to add to the mask.",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginNetworkSteeringMaskSetCommandArguments[] = {
  "The channel mask to subtract the channel from.",
  "The value to set the channel mask to.",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginNetworkSteeringMaskSubtractCommandArguments[] = {
  "The channel mask to subtract the channel from.",
  "The channel to subtract the mask from.",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginNetworkSteeringMaskCommands[] = {
  emberCommandEntryActionWithDetails("add", emberAfPluginNetworkSteeringChannelAddOrSubtractCommand, "uu", "Adds a channel to either the primary or secondary channel mask of the  ...", emberCommandTablePluginNetworkSteeringMaskAddCommandArguments),
  emberCommandEntryActionWithDetails("set", emberAfPluginNetworkSteeringChannelSetCommand, "uw", "Set either the primary or secondary channel mask.", emberCommandTablePluginNetworkSteeringMaskSetCommandArguments),
  emberCommandEntryActionWithDetails("subtract", emberAfPluginNetworkSteeringChannelAddOrSubtractCommand, "uu", "Subtracts a channel from either the primary or secondary channel mask  ...", emberCommandTablePluginNetworkSteeringMaskSubtractCommandArguments),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginNetworkSteeringStartCommandArguments[] = {
  "A mask of options for indicating specific behavior within the network- ...",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginNetworkSteeringCommands[] = {
  emberCommandEntrySubMenu("mask", emberCommandTablePluginNetworkSteeringMaskCommands, ""),
  emberCommandEntryActionWithDetails("start", emberAfPluginNetworkSteeringStartCommand, "u", "Starts the network steering process.", emberCommandTablePluginNetworkSteeringStartCommandArguments),
  emberCommandEntryActionWithDetails("status", emberAfPluginNetworkSteeringStatusCommand, "", "Displays the current status of the network steering process.", NULL),
  emberCommandEntryActionWithDetails("stop", emberAfPluginNetworkSteeringStopCommand, "", "Stops the network steering process.", NULL),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTablePluginMfglibToneCommands[] = {
  emberCommandEntryActionWithDetails("start", emAfMfglibToneStartCommand, "", "Starts a tone test.", NULL),
  emberCommandEntryActionWithDetails("stop", emAfMfglibToneStopCommand, "", "Stops the tone test.", NULL),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTablePluginMfglibStreamCommands[] = {
  emberCommandEntryActionWithDetails("start", emAfMfglibStreamStartCommand, "", "Start the stream test.", NULL),
  emberCommandEntryActionWithDetails("stop", emAfMfglibStreamStopCommand, "", "Stop the stream test.", NULL),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibSendMessageCommandArguments[] = {
  "The hex data to send, up to 16 bytes.",
  "The number of packets to send.",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibSendRandomCommandArguments[] = {
  "The number of packets to send.",
  "The length of the packet to send.",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibSendTestCommandArguments[] = {
  "The number of packets to send.",
  "The length of the packet to send.",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginMfglibSendCommands[] = {
  emberCommandEntryActionWithDetails("message", emAfMfglibSendMessageCommand, "bv", "Send a test message with the specified data in it.", emberCommandTablePluginMfglibSendMessageCommandArguments),
  emberCommandEntryActionWithDetails("random", emAfMfglibSendCommand, "vu", "Send a series of test packets with random data..", emberCommandTablePluginMfglibSendRandomCommandArguments),
  emberCommandEntryActionWithDetails("test", emAfMfglibSendCommand, "vu", "Send a series of test packets with fixed data.", emberCommandTablePluginMfglibSendTestCommandArguments),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibMfgenableCommandArguments[] = {
  "1 = enable, 0 = disable.",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibProgramEuiCommandArguments[] = {
  "IEEE address to program.",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibSetChannelCommandArguments[] = {
  "The 802.15.4 channel number.",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibSetOptionsCommandArguments[] = {
  "The options bitmask (0 = normal transmit, 1 = CSMA transmit).",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibSetPowerCommandArguments[] = {
  "The power level",
  "The power mode",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibSleepCommandArguments[] = {
  "Sleep duration (mS).",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginMfglibStartCommandArguments[] = {
  "Use the Rx callback.",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginMfglibCommands[] = {
  emberCommandEntryActionWithDetails("mfgenable", emAfMfglibEnableMfglib, "u", "Enable mfglib.", emberCommandTablePluginMfglibMfgenableCommandArguments),
  emberCommandEntryActionWithDetails("programEui", emAfMfglibProgramEuiCommand, "b", "Program EUI.", emberCommandTablePluginMfglibProgramEuiCommandArguments),
  emberCommandEntrySubMenu("send", emberCommandTablePluginMfglibSendCommands, ""),
  emberCommandEntryActionWithDetails("set-channel", emAfMfglibSetChannelCommand, "u", "Sets the channel used by the manufacturing library for testing.", emberCommandTablePluginMfglibSetChannelCommandArguments),
  emberCommandEntryActionWithDetails("set-options", emAfMfglibSetOptions, "u", "Sets options in the manufacturing library for testing.", emberCommandTablePluginMfglibSetOptionsCommandArguments),
  emberCommandEntryActionWithDetails("set-power", emAfMfglibSetPowerAndModeCommand, "sv", "Set the power level and mode for the manufacturing test.", emberCommandTablePluginMfglibSetPowerCommandArguments),
  emberCommandEntryActionWithDetails("sleep", emAfMfglibSleepCommand, "v", "Sleep.", emberCommandTablePluginMfglibSleepCommandArguments),
  emberCommandEntryActionWithDetails("start", emAfMfglibStartCommand, "u", "Start the mfglib test mode.", emberCommandTablePluginMfglibStartCommandArguments),
  emberCommandEntryActionWithDetails("status", emAfMfglibStatusCommand, "", "Prints the current status of the manufacturing library.", NULL),
  emberCommandEntryActionWithDetails("stop", emAfMfglibStopCommand, "", "Stop the mfglib test mode.", NULL),
  emberCommandEntrySubMenu("stream", emberCommandTablePluginMfglibStreamCommands, ""),
  emberCommandEntrySubMenu("tone", emberCommandTablePluginMfglibToneCommands, ""),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTablePluginIdentifyCommands[] = {
  emberCommandEntryActionWithDetails("print", emAfPluginIdentifyCliPrint, "", "Print which endpoints are reporting.", NULL),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTablePluginGroupsServerCommands[] = {
  emberCommandEntryActionWithDetails("clear", emAfGroupsServerCliClear, "", "Clear the groups table on every endpoint.", NULL),
  emberCommandEntryActionWithDetails("print", emAfGroupsServerCliPrint, "", "Print information about the contents of the groups table.", NULL),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginGreenPowerClientAddGroupSinkCommandArguments[] = {
  "GPD Source ID",
  "Sink group",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginGreenPowerClientAddSinkCommandArguments[] = {
  "GPD Source ID",
  "Sink's IEEE address",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginGreenPowerClientDuplicateFilterTestCommandArguments[] = {
  "endpoint",
  "source Id of the fake incoming message",
  "sequence number",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginGreenPowerClientRmGpdCommandArguments[] = {
  "GPD Source ID",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginGreenPowerClientRmSinkCommandArguments[] = {
  "GPD Source ID",
  "Sink's IEEE address",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginGreenPowerClientSetKeyCommandArguments[] = {
  "index",
  "source Id of the fake incoming message",
  NULL
};
#endif

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginGreenPowerClientSetProxyEntryCommandArguments[] = {
  "index to proxy table",
  "GPD Source ID",
  "Sink's node address",
  "options",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginGreenPowerClientCommands[] = {
  emberCommandEntryActionWithDetails("add-group-sink", emberAfPluginGreenPowerClientAddGroupcastSink, "wv", "Add a groupcast sink for a given GPD", emberCommandTablePluginGreenPowerClientAddGroupSinkCommandArguments),
  emberCommandEntryActionWithDetails("add-sink", emberAfPluginGreenPowerClientAddSink, "wb", "Add a sink for a given GPD", emberCommandTablePluginGreenPowerClientAddSinkCommandArguments),
  emberCommandEntryActionWithDetails("clear-proxy-table", emberAfPluginGreenPowerClientClearProxyTable, "", "clear the proxy table", NULL),
  emberCommandEntryActionWithDetails("duplicate-filter-test", emberAfPluginGreenPowerClientDuplicateFilteringTest, "uwu", "This is used to instrument the current device receiving a message in o ...", emberCommandTablePluginGreenPowerClientDuplicateFilterTestCommandArguments),
  emberCommandEntryActionWithDetails("print-proxy-table", emberAfPluginGreenPowerClientPrintProxyTable, "", "Print the proxy table", NULL),
  emberCommandEntryActionWithDetails("rm-gpd", emberAfPluginGreenPowerClientRemoveProxyTableEntry, "w", "Remove a given GPD from the proxy table", emberCommandTablePluginGreenPowerClientRmGpdCommandArguments),
  emberCommandEntryActionWithDetails("rm-sink", emberAfPluginGreenPowerClientAddSink, "wb", "remove a sink for a given GP ...", emberCommandTablePluginGreenPowerClientRmSinkCommandArguments),
  emberCommandEntryActionWithDetails("set-key", emberAfPluginGreenPowerClientSetKey, "ub", "This is used to set the key for a proxy table entry", emberCommandTablePluginGreenPowerClientSetKeyCommandArguments),
  emberCommandEntryActionWithDetails("set-proxy-entry", emberAfPluginGreenPowerClientSetProxyEntry, "uwvw", "Set a proxy table entry", emberCommandTablePluginGreenPowerClientSetProxyEntryCommandArguments),
  emberCommandEntryTerminator()
};

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static PGM_P PGM emberCommandTablePluginConnectionManagerSetForceShortPollCommandArguments[] = {
  "1 to permanently force short polling, 0 to behave as normal (default).",
  NULL
};
#endif

static EmberCommandEntry emberCommandTablePluginConnectionManagerCommands[] = {
  emberCommandEntryActionWithDetails("set-force-short-poll", emAfPluginConnectionManagerSetForceShortPollCommand, "u", "Can be used to force the device to permanently poll on a short interva ...", emberCommandTablePluginConnectionManagerSetForceShortPollCommandArguments),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTablePluginCommands[] = {
  emberCommandEntrySubMenu("connection-manager", emberCommandTablePluginConnectionManagerCommands, ""),
  emberCommandEntrySubMenu("green-power-client", emberCommandTablePluginGreenPowerClientCommands, ""),
  emberCommandEntrySubMenu("groups-server", emberCommandTablePluginGroupsServerCommands, ""),
  emberCommandEntrySubMenu("identify", emberCommandTablePluginIdentifyCommands, ""),
  emberCommandEntrySubMenu("mfglib", emberCommandTablePluginMfglibCommands, ""),
  emberCommandEntrySubMenu("network-steering", emberCommandTablePluginNetworkSteeringCommands, ""),
  emberCommandEntrySubMenu("ota-bootload", emberCommandTablePluginOtaBootloadCommands, ""),
  emberCommandEntrySubMenu("ota-client", emberCommandTablePluginOtaClientCommands, ""),
  emberCommandEntrySubMenu("ota-storage-common", emberCommandTablePluginOtaStorageCommonCommands, ""),
  emberCommandEntrySubMenu("ota-storage-eeprom", emberCommandTablePluginOtaStorageEepromCommands, ""),
  emberCommandEntrySubMenu("reporting", emberCommandTablePluginReportingCommands, ""),
  emberCommandEntrySubMenu("scenes", emberCommandTablePluginScenesCommands, ""),
  emberCommandEntryTerminator()
};

static EmberCommandEntry emberCommandTableNetworkCommands[] = {
  emberCommandEntryActionWithDetails("leave", networkLeaveCommand, "", "Leave the current network.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTable[] = {
  emberCommandEntrySubMenu("network", emberCommandTableNetworkCommands, ""),
  emberCommandEntrySubMenu("plugin", emberCommandTablePluginCommands, ""),
  emberCommandEntrySubMenu("zcl", emberCommandTableZclCommands, ""),
  CUSTOM_COMMANDS
  emberCommandEntryTerminator()
};



